// Generates a self-contained Python import script tailored to the template the
// visitor built. Stdlib XML-RPC + openpyxl; uses Odoo's "load" method so it
// behaves exactly like the import screen (External ID = idempotent re-runs).
// String.raw keeps Python's "\n" escapes intact inside the JS template literal.

export function generateImportScript({ model, fields, version }) {
  const filename = `odoo${version}_${model.slug}_import_template.xlsx`
  const scriptName = `import_${model.slug.replace(/-/g, '_')}.py`
  const columns = fields.map((f) => `    "${f.name}",`).join('\n')

  return String.raw`#!/usr/bin/env python3
"""Import ${model.name} into Odoo ${version} — generated by Odoo Import Templates.

What this script does:
  Reads your filled-in Excel template (sheet "Import Template") and imports it
  into ${model.id} using Odoo's own import engine ("load"). It behaves exactly
  like Odoo's import screen: the "id" column (External ID) makes re-runs UPDATE
  existing records instead of creating duplicates.

Before you run it:
  1. pip install openpyxl
  2. Create an API key in Odoo: click your avatar -> My Profile (or Preferences)
     -> Account Security -> New API Key.
  3. Make a database backup, and do a small test run first (set LIMIT = 10).

Usage:
  export ODOO_API_KEY=your_key          # or let the script prompt you
  python ${scriptName} [path/to/${filename}]
"""

import os
import sys
import getpass
import xmlrpc.client

# ---- EDIT THESE -------------------------------------------------------------
URL = "https://yourcompany.odoo.com"  # your Odoo address, without trailing slash
DB = "yourcompany"                    # database name (Odoo Online: first part of the URL)
USERNAME = "admin@yourcompany.com"    # your Odoo login email
# ------------------------------------------------------------------------------

MODEL = "${model.id}"
DEFAULT_FILE = "${filename}"
SHEET = "Import Template"
BATCH_SIZE = 500
LIMIT = None  # set to e.g. 10 for a small test run first

EXPECTED_COLUMNS = [
${columns}
]


def main():
    try:
        from openpyxl import load_workbook
    except ImportError:
        sys.exit("openpyxl is not installed. Run:  pip install openpyxl")

    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_FILE
    if not os.path.exists(path):
        sys.exit(f"File not found: {path}\n"
                 f"Usage: python {os.path.basename(sys.argv[0])} path/to/{DEFAULT_FILE}")

    wb = load_workbook(path, read_only=True, data_only=True)
    if SHEET not in wb.sheetnames:
        sys.exit(f'Sheet "{SHEET}" not found in {path}. '
                 "Use the file downloaded from the template generator.")
    rows = list(wb[SHEET].iter_rows(values_only=True))
    if not rows:
        sys.exit("The sheet is empty.")

    header = [str(h).strip() for h in rows[0] if h is not None]
    unknown = [h for h in header
               if h not in EXPECTED_COLUMNS
               and not h.endswith("/id") and not h.endswith("/.id")]
    if unknown:
        print("WARNING: unexpected column(s): " + ", ".join(unknown)
              + " — check for typos. Continuing anyway.")

    data = []
    for row in rows[1:]:
        values = ["" if v is None else str(v).strip() for v in row[:len(header)]]
        if any(values):
            data.append(values)
    if not data:
        sys.exit("No data rows found. Did you delete the example row "
                 "and forget to add your own data?")
    if LIMIT:
        data = data[:LIMIT]
        print(f"TEST RUN: importing only the first {len(data)} row(s). "
              "Set LIMIT = None for the full import.")

    api_key = os.environ.get("ODOO_API_KEY") or getpass.getpass("Odoo API key (input hidden): ")
    common = xmlrpc.client.ServerProxy(f"{URL}/xmlrpc/2/common")
    try:
        uid = common.authenticate(DB, USERNAME, api_key, {})
    except Exception as exc:
        sys.exit(f"Could not reach {URL}: {exc}")
    if not uid:
        sys.exit("Authentication failed — check URL, DB, USERNAME and your API key.")
    models = xmlrpc.client.ServerProxy(f"{URL}/xmlrpc/2/object")

    print(f"Importing {len(data)} row(s) into {MODEL} at {URL} ...")
    imported = failed = 0
    for start in range(0, len(data), BATCH_SIZE):
        batch = data[start:start + BATCH_SIZE]
        result = models.execute_kw(DB, uid, api_key, MODEL, "load", [header, batch])
        ids = result.get("ids") or []
        for msg in result.get("messages") or []:
            excel_row = start + msg.get("record", 0) + 2  # +1 header, +1 one-based
            print(f"  [{str(msg.get('type', 'info')).upper()}] "
                  f"Excel row {excel_row}: {msg.get('message')}")
        if ids:
            imported += len(ids)
        else:
            failed += len(batch)
        print(f"Batch {start // BATCH_SIZE + 1}: {len(ids)}/{len(batch)} row(s) imported")

    if failed:
        sys.exit(f"\nDONE WITH ERRORS: {imported} imported, {failed} failed. "
                 "Fix the rows above and simply run the script again — "
                 "the id column makes re-runs safe (update, not duplicate).")
    print(f"\nDONE: {imported} row(s) imported into {MODEL}. "
          "Re-running with the same id values updates these records.")


if __name__ == "__main__":
    main()
`
}
